# concatinate js files
less ../src/lib/loca.js > sucodo_release.js
less ../src/js/sucodonamespace.js >> sucodo_release.js
less ../src/js/loca_data.js >> sucodo_release.js
less ../src/js/storage.js >> sucodo_release.js
less ../src/js/textanalyzer.js >> sucodo_release.js
less ../src/js/textbreaker.js >> sucodo_release.js
less ../src/js/websearcher_google.js >> sucodo_release.js
less ../src/js/textmarkup.js >> sucodo_release.js
less ../src/js/resultview.js >> sucodo_release.js
less ../src/js/colorwarner.js >> sucodo_release.js
less ../src/js/sucodoloca.js >> sucodo_release.js
less ../src/js/sucodo.js >> sucodo_release.js
